"""v2_likes_chamados_turma_arquivada

Revision ID: 4845a79d3a2b
Revises: e614d240e2fd
Create Date: 2026-06-10 10:27:34.007790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4845a79d3a2b'
down_revision = 'e614d240e2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chamado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('duvida', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolvido', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('resposta_admin', sa.Text(), nullable=True),
    sa.Column('respondido_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('permite_chamado', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivada', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turma', schema=None) as batch_op:
        batch_op.drop_column('arquivada')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('permite_chamado')
        batch_op.drop_column('likes')

    op.drop_table('chamado')
    # ### end Alembic commands ###
