"""configuracao_storage

Revision ID: c1e17f34506b
Revises: 4845a79d3a2b
Create Date: 2026-06-12 09:52:55.132123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e17f34506b'
down_revision = '4845a79d3a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('chave')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracao')
    # ### end Alembic commands ###
